/*
  Static reference/business-logic tables only — never fabricated infrastructure
  data. Department list and the Alert/Knowledge Base linking content live here
  because they're app configuration, not pretend AD/FortiGate/printer records.
*/

export const DEPARTMENTS = ['IT', 'Finance', 'Sales', 'HR', 'Marketing', 'Operations'];

// Alert type -> KB / impact / first-checks linking table (Alerts page + Assistant fallback).
export const ALERT_LINKS = {
 'AD Account Locked':{impact:'The affected user cannot authenticate until the account is unlocked.',kb:'KB-AD-001',checks:['Confirm the lockout with Get-ADUser -Properties LockedOut','Check Event ID 4740 on the domain controller for the source of the bad password attempts','Verify the user is not using a cached credential on another device or mobile mail client','Unlock the account and ask the user to re-authenticate']},
 'Printer Offline':{impact:'Users at the affected location cannot print until connectivity is restored.',kb:'KB-PRN-001',checks:['Ping the printer IP address','Check the printer power and network cable / Wi-Fi status at the device','Confirm the switch port or access point serving the printer is up','Check for a recent DHCP lease change or IP conflict']},
 'Toner Critical':{impact:'The printer will stop producing legible output and may pause the print queue.',kb:'KB-PRN-002',checks:['Confirm the reported toner percentage on the device panel','Check Toner Inventory for the matching consumable and current stock','Confirm the correct department/cost center for replacement','Replace the toner cartridge and reset the counter if required']},
 'WAN Down':{impact:'Internet-dependent services (cloud apps, email, remote VPN) may be degraded or unavailable.',kb:'KB-FTG-002',checks:['Check physical link and ISP modem/ONT status','Confirm the interface status in the FortiGate dashboard','Test failover to the secondary WAN link','Contact the ISP with the circuit ID if the link stays down']},
 'FortiGate High CPU':{impact:'Firewall throughput and VPN performance may degrade, risking dropped sessions.',kb:'KB-FTG-001',checks:['Identify top CPU-consuming processes/proxies on the FortiGate','Check for an active IPS/AV scan spike or DoS pattern','Review concurrent session count against the device baseline','Review recent policy or signature changes']},
 'VPN Down':{impact:'Remote connectivity for the affected branch or remote users may be unavailable.',kb:'KB-FTG-010',checks:['Check Phase 1 (IKE) status','Check Phase 2 (IPsec SA) status','Confirm peer/remote gateway reachability','Confirm the WAN interface used by the tunnel is up','Review VPN logs for negotiation errors']},
 'Inactive Computer':{impact:'The device may be stale, powered off permanently, or missing security patches — a hygiene and security risk.',kb:'KB-AD-005',checks:['Confirm the device is not simply powered off long-term (leaver, seasonal, spare)','Check whether the assigned user still requires the device','Verify patch/AV compliance status if the device reappears online','Disable or decommission the computer object if confirmed retired']},
 'Password Expiring':{impact:'Users will be locked out of domain and email/VPN access once the password expires.',kb:'KB-AD-002',checks:['Identify all accounts with passwords expiring within 7 days','Notify affected users with reset instructions','Confirm self-service password reset is available for remote users','Escalate any expiring service account passwords separately']},
};

export const KB_CATEGORIES = ['All','Active Directory','FortiGate','Networking','Printers','Windows','Microsoft 365','Security','Applications','Troubleshooting','SOP','Policies'];

export const KB_ARTICLES = [
{code:'KB-AD-001',title:'Unlock Active Directory Account',category:'Active Directory',tags:['account locked','lockout','authentication','unlock'],
 purpose:'Restore sign-in access for a user whose account has been locked out by policy.',
 problem:'User cannot authenticate because the account is locked.',
 symptoms:['User reports "account is locked" or "too many attempts" at logon','Event ID 4740 logged on a domain controller'],
 requirements:['Help Desk or Account Operators AD permissions','Active Directory PowerShell module'],
 procedure:['Verify the user identity.','Check whether the account is locked.','Unlock the account.','Ask the user to authenticate again.','Verify successful login.'],
 commands:[{cmd:'Get-ADUser username -Properties LockedOut',verifies:'Confirms current lockout state before acting'},{cmd:'Unlock-ADAccount -Identity username',verifies:'Clears the lockout flag'}],
 verification:'Get-ADUser username -Properties LockedOut',
 expectedResult:'LockedOut = False',
 rollback:'Not applicable — unlocking is non-destructive. If the account re-locks immediately, investigate the source device before repeating.',
 notes:'If lockouts recur within minutes, check for a cached credential on a phone or mapped drive before unlocking again.'},
{code:'KB-AD-002',title:'Reset an Expired or Expiring Password',category:'Active Directory',tags:['password expiry','reset','expiring'],
 purpose:'Restore access for a user whose password has expired or is about to expire.',
 problem:'User cannot log on because their password has expired, or will expire within days.',
 symptoms:['Logon prompt shows "Your password has expired"','Password Expiry date is within 7 days in AD'],
 requirements:['Help Desk AD permissions'],
 procedure:['Confirm identity of the requesting user.','Check current PasswordLastSet and expiry policy.','Reset the password or ask the user to change it via Ctrl+Alt+Del.','Set "User must change password at next logon" if resetting on their behalf.','Confirm the new expiry date.'],
 commands:[{cmd:'Get-ADUser username -Properties PasswordExpired,PasswordLastSet',verifies:'Confirms expiry status'},{cmd:'Set-ADAccountPassword -Identity username -Reset -NewPassword (Read-Host -AsSecureString)',verifies:'Applies a new password'},{cmd:'Set-ADUser username -ChangePasswordAtLogon $true',verifies:'Forces the user to set their own password on next logon'}],
 verification:'Get-ADUser username -Properties PasswordLastSet',
 expectedResult:'PasswordLastSet reflects today’s date',
 rollback:'None required.',
 notes:'Never communicate a temporary password over an unencrypted channel.'},
{code:'KB-AD-003',title:'Enable a Disabled Active Directory Account',category:'Active Directory',tags:['disabled account','enable','offboarding','reinstate'],
 purpose:'Reinstate access for a user whose account was disabled (return from leave, re-hire, incorrect offboarding).',
 problem:'User cannot authenticate because the account is disabled.',
 symptoms:['Logon fails with no lockout message','Get-ADUser shows Enabled = False'],
 requirements:['Manager or HR confirmation that the account should be reinstated'],
 procedure:['Confirm with HR/manager that reinstatement is authorized.','Check the account is not disabled as part of an active offboarding.','Enable the account.','Confirm password status and reset if required.','Ask the user to log on.'],
 commands:[{cmd:'Get-ADUser username -Properties Enabled',verifies:'Confirms current state'},{cmd:'Enable-ADAccount -Identity username',verifies:'Enables the account'}],
 verification:'Get-ADUser username -Properties Enabled',
 expectedResult:'Enabled = True',
 rollback:'Disable-ADAccount -Identity username',
 notes:'Never re-enable an account that was disabled as part of a security incident without explicit sign-off.'},
{code:'KB-AD-004',title:'Domain Login Troubleshooting',category:'Active Directory',tags:['cannot login','domain login','authentication failure'],
 purpose:'Diagnose a general "cannot log in to domain" report.',
 problem:'User cannot login to domain.',
 symptoms:['Logon fails at the Windows lock screen','"The trust relationship" or generic authentication error'],
 requirements:['Network line of sight to a domain controller from the workstation'],
 procedure:['Is the user account locked?','Is the account disabled?','Is the password expired?','Can the workstation communicate with a domain controller?','Is DNS pointing to the correct internal DNS server?'],
 commands:[{cmd:'Get-ADUser username -Properties LockedOut,Enabled,PasswordExpired',verifies:'Checks lockout, enabled and expiry state in one call'},{cmd:'Test-NetConnection dc01.contoso.local -Port 389',verifies:'Confirms LDAP reachability to a domain controller'},{cmd:'nslookup contoso.local',verifies:'Confirms the workstation resolves the domain via internal DNS'},{cmd:'ipconfig /all',verifies:'Confirms the workstation is using an internal DNS server, not a public one'}],
 verification:'Retry logon after remediating the failing check above',
 expectedResult:'User authenticates successfully',
 rollback:'Not applicable.',
 notes:'Recommended KB pairing: KB-AD-001 (Account Lock Troubleshooting), KB-AD-004 (this article).'},
{code:'KB-AD-005',title:'Identify and Clean Up Inactive Computer Accounts',category:'Active Directory',tags:['inactive computer','stale device','cleanup','offline'],
 purpose:'Identify workstations/servers that have not contacted a domain controller recently and decide whether to retire them.',
 problem:'A computer object has not authenticated to the domain in 30+ days.',
 symptoms:['LastLogonTimestamp older than 30 days','Device does not appear on the network scan'],
 requirements:['Asset records to confirm the device owner/status'],
 procedure:['Query computers inactive beyond the threshold.','Cross-check against the asset register for known spares/seasonal devices.','Contact the assigned user or department if unclear.','Disable the computer object if retirement is confirmed.','Remove from AD after a grace period per the retention policy.'],
 commands:[{cmd:"Get-ADComputer -Filter * -Properties LastLogonTimestamp | Where-Object { [DateTime]::FromFileTime($_.LastLogonTimestamp) -lt (Get-Date).AddDays(-30) }",verifies:'Lists computers inactive for 30+ days'},{cmd:'Disable-ADAccount -Identity COMPUTERNAME$',verifies:'Disables a confirmed-retired computer object'}],
 verification:'Get-ADComputer COMPUTERNAME -Properties Enabled',
 expectedResult:'Enabled = False (once retirement confirmed)',
 rollback:'Enable-ADAccount -Identity COMPUTERNAME$',
 notes:'Do not disable a device before confirming with the assigned department — some laptops are inactive due to long leave, not retirement.'},
{code:'KB-FTG-001',title:'FortiGate High CPU Troubleshooting',category:'FortiGate',tags:['high cpu','performance','fortigate slow'],
 purpose:'Diagnose sustained high CPU utilization on a FortiGate appliance.',
 problem:'FortiGate CPU utilization is high and impacting throughput.',
 symptoms:['Dashboard shows sustained CPU above baseline','Users report slow browsing or VPN performance'],
 requirements:['FortiGate admin console or CLI access'],
 procedure:['Identify which daemon/proxy is consuming CPU.','Check for an active AV/IPS scan spike or DoS/flood pattern.','Review session count against the device’s rated capacity.','Check for recent policy, signature or firmware changes.','Consider disabling non-essential deep inspection temporarily if capacity-bound.'],
 commands:[{cmd:'get system performance status',verifies:'Shows current CPU/memory snapshot'},{cmd:'diagnose sys top',verifies:'Shows per-process CPU consumption'},{cmd:'diagnose sys session list | wc -l',verifies:'Confirms current session count'}],
 verification:'get system performance status',
 expectedResult:'CPU utilization returns to baseline (typically under 70% sustained)',
 rollback:'Re-enable any inspection profile that was temporarily disabled once load normalizes.',
 notes:'Sustained high CPU combined with a session spike can indicate a DoS attempt — review logs before assuming a capacity issue.'},
{code:'KB-FTG-002',title:'FortiGate WAN Interface Down Troubleshooting',category:'FortiGate',tags:['wan down','internet down','no internet'],
 purpose:'Restore connectivity when a WAN interface reports down.',
 problem:'A WAN interface on the FortiGate is down, affecting internet-dependent services.',
 symptoms:['Interface status shows down in the dashboard','Users report no internet access'],
 requirements:['Physical or remote access to the FortiGate and modem/ONT'],
 procedure:['Check the physical link light on the FortiGate port and the ISP modem/ONT.','Confirm the interface status and IP assignment on the FortiGate.','Restart the modem/ONT if the carrier link is down.','Fail over to the secondary WAN link if configured.','Contact the ISP with the circuit ID if the outage persists.'],
 commands:[{cmd:'get system interface physical',verifies:'Shows link state per physical interface'},{cmd:'diagnose hardware deviceinfo nic wan1',verifies:'Shows link/speed/duplex detail for the WAN NIC'},{cmd:'execute ping 8.8.8.8',verifies:'Confirms upstream reachability once link is restored'}],
 verification:'get system interface physical',
 expectedResult:'WAN interface shows link: up',
 rollback:'Not applicable.',
 notes:'Always confirm secondary WAN failover engaged correctly so users are not silently degraded.'},
{code:'KB-FTG-003',title:'SSL VPN Connectivity Troubleshooting',category:'FortiGate',tags:['vpn down','ssl vpn','remote access','vpn is down'],
 purpose:'Diagnose remote users unable to connect via SSL VPN (FortiClient).',
 problem:'Remote users cannot establish an SSL VPN connection.',
 symptoms:['FortiClient shows a connection or authentication error','SSL VPN portal is unreachable from outside the network'],
 requirements:['FortiGate admin access', 'Affected user’s FortiClient version'],
 procedure:['Confirm the SSL VPN service is enabled on the expected WAN interface/port.','Check the user’s account is enabled and not locked in the auth source.','Review SSL VPN logs for the failed session.','Confirm the user’s FortiClient version is supported.','Test from a known-good external network to isolate ISP-side blocking.'],
 commands:[{cmd:'get vpn ssl monitor',verifies:'Lists currently connected SSL VPN sessions'},{cmd:'diagnose debug application sslvpn -1',verifies:'Streams live SSL VPN negotiation debug output'},{cmd:'diagnose vpn ssl list',verifies:'Shows detailed state of active/attempted SSL VPN sessions'}],
 verification:'get vpn ssl monitor',
 expectedResult:'User session appears as connected',
 rollback:'diagnose debug disable (turn off debug output once resolved)',
 notes:'Distinct from KB-FTG-010, which covers site-to-site IPsec tunnels rather than individual remote users.'},
{code:'KB-FTG-004',title:'VLAN and Switch Interface Troubleshooting',category:'Networking',tags:['vlan','switch port','no network','connectivity'],
 purpose:'Diagnose a device that cannot reach network resources on a specific VLAN.',
 problem:'A device or group of devices on a VLAN has no or partial connectivity.',
 symptoms:['Device shows "limited connectivity" or no IP','Devices on one VLAN cannot reach another VLAN they are permitted to reach'],
 requirements:['Access to the FortiGate interface/VLAN configuration and managed switch'],
 procedure:['Confirm the device’s switch port VLAN assignment.','Confirm the FortiGate VLAN interface is up and has the expected policies.','Check inter-VLAN firewall policy allows the required traffic.','Check for a duplicate IP or exhausted DHCP scope on that VLAN.'],
 commands:[{cmd:'diagnose netlink interface list',verifies:'Lists VLAN interfaces and their state'},{cmd:'get router info routing-table all',verifies:'Confirms routes exist between VLANs'}],
 verification:'Ping between a host on the VLAN and a known-good resource',
 expectedResult:'Successful reply with expected latency',
 rollback:'Revert any policy change made during testing.',
 notes:'CCTV and IoT devices (e.g. Hikvision cameras) are commonly segmented onto a dedicated VLAN — confirm segmentation before assuming a fault.'},
{code:'KB-FTG-010',title:'IPsec VPN Tunnel Troubleshooting',category:'FortiGate',tags:['ipsec','tunnel down','site to site vpn','vpn tunnel down'],
 purpose:'Restore a site-to-site IPsec VPN tunnel that has gone down.',
 problem:'An IPsec VPN tunnel to a branch or DR site is down.',
 symptoms:['Tunnel shows down in the VPN monitor','Branch site loses connectivity to HQ resources'],
 requirements:['FortiGate admin access at the local end (and peer end if reachable)'],
 procedure:['Check Phase 1 (IKE) status.','Check Phase 2 (IPsec SA) status.','Confirm peer reachability.','Confirm the local WAN interface used by the tunnel is up.','Review VPN logs for negotiation failures (e.g. PSK or proposal mismatch).'],
 commands:[{cmd:'diagnose vpn ike gateway list',verifies:'Shows Phase 1 status per tunnel'},{cmd:'diagnose vpn tunnel list',verifies:'Shows Phase 2 SA status per tunnel'},{cmd:'execute ping <peer-ip>',verifies:'Confirms basic reachability to the remote peer'}],
 verification:'diagnose vpn tunnel list',
 expectedResult:'Tunnel status shows selectors and SA as established',
 rollback:'Not applicable.',
 notes:'If Phase 1 fails immediately, suspect a PSK or proposal mismatch after a recent config change on either end.'},
{code:'KB-NET-001',title:'Workstation Cannot Obtain a DHCP Address',category:'Networking',tags:['dhcp','no ip address','apipa','pc cannot get dhcp'],
 purpose:'Resolve a workstation that cannot obtain an IP address from DHCP.',
 problem:'PC cannot get DHCP / shows an APIPA (169.254.x.x) address.',
 symptoms:['ipconfig shows 169.254.x.x','No network access, "unidentified network" in Windows'],
 requirements:['Physical or remote access to the affected workstation'],
 procedure:['Confirm the network cable/Wi-Fi association is active.','Release and renew the IP address.','Confirm the switch port VLAN and DHCP scope has available leases.','Check for a rogue DHCP server on the segment.','Verify the DHCP relay/helper address on the VLAN if it is a routed network.'],
 commands:[{cmd:'ipconfig /release',verifies:'Releases the current (invalid) lease'},{cmd:'ipconfig /renew',verifies:'Requests a new lease from DHCP'},{cmd:'ipconfig /all',verifies:'Confirms the new address, gateway and DNS servers assigned'}],
 verification:'ipconfig /all',
 expectedResult:'Workstation receives a valid address from the expected scope (e.g. 192.168.10.0/24)',
 rollback:'Not applicable.',
 notes:'A scope showing 0 available leases is a common root cause — check DHCP scope utilization before assuming a client-side fault.'},
{code:'KB-NET-002',title:'General Wired/Wireless Connectivity Troubleshooting',category:'Networking',tags:['no network','wifi down','ethernet','connectivity'],
 purpose:'Triage a general loss of network connectivity report.',
 problem:'A user reports no network / internet access.',
 symptoms:['Cannot reach internal or external resources','Intermittent drops'],
 requirements:[],
 procedure:['Confirm scope: one user, one floor, or site-wide.','Check physical link/Wi-Fi signal at the device.','Check DHCP address is valid (see KB-NET-001).','Check the relevant switch/AP/FortiGate interface status.','Escalate to FortiGate WAN troubleshooting (KB-FTG-002) if site-wide.'],
 commands:[{cmd:'Test-NetConnection 8.8.8.8',verifies:'Confirms external reachability'},{cmd:'Test-NetConnection contoso.local -Port 389',verifies:'Confirms internal domain controller reachability'}],
 verification:'Test-NetConnection 8.8.8.8',
 expectedResult:'PingSucceeded = True',
 rollback:'Not applicable.',
 notes:''},
{code:'KB-PRN-001',title:'Printer Showing Offline',category:'Printers',tags:['printer offline','cannot print','printer not responding'],
 purpose:'Restore a printer that is showing offline.',
 problem:'Printer showing offline / not responding to print jobs.',
 symptoms:['Printer status shows offline on the print server or dashboard','Print jobs stuck in the queue'],
 requirements:['Network access to the printer IP'],
 procedure:['Ping the printer IP address.','Check the printer’s network cable / Wi-Fi status at the device panel.','Confirm the switch port or access point serving the printer is up.','Restart the print spooler on the print server if the device itself responds to ping.','Re-add the printer if the IP address changed.'],
 commands:[{cmd:'ping 192.168.10.31',verifies:'Confirms the printer responds on the network'},{cmd:'Restart-Service -Name Spooler',verifies:'Clears a stuck print spooler service'},{cmd:'Get-Printer | Where-Object PrinterStatus -ne "Normal"',verifies:'Lists printers currently reporting a non-normal status'}],
 verification:'ping <printer-ip>',
 expectedResult:'Printer replies and status returns to Online/Ready',
 rollback:'Not applicable.',
 notes:''},
{code:'KB-PRN-002',title:'Replacing Toner / Critical Toner Level',category:'Printers',tags:['toner critical','low toner','replace toner'],
 purpose:'Respond to a printer reporting critical toner level.',
 problem:'Printer toner level is critical and output quality is degrading or about to stop.',
 symptoms:['Toner percentage below 10% on the dashboard','Faded or streaked printed output'],
 requirements:['Matching toner cartridge available in inventory'],
 procedure:['Confirm the toner percentage on the device panel matches the dashboard reading.','Look up the compatible toner model in Toner Inventory.','Confirm sufficient stock; escalate a purchase request if below minimum.','Replace the cartridge and reset the toner counter if the model supports it.','Log the transaction as an Issue in Toner Inventory.'],
 commands:[],
 verification:'Check toner level on the device panel after replacement',
 expectedResult:'Toner level reads at or near 100% after cartridge replacement',
 rollback:'Not applicable.',
 notes:'Always log the Issue transaction so stock levels stay accurate for reordering.'},
{code:'KB-WIN-001',title:'Windows Workstation Slow Performance / Freeze',category:'Windows',tags:['slow pc','freeze','high cpu workstation','not responding'],
 purpose:'Diagnose a Windows workstation running slowly or freezing.',
 problem:'Workstation is slow, unresponsive, or freezes intermittently.',
 symptoms:['Applications take a long time to open','Explorer or the desktop becomes unresponsive'],
 requirements:['Local admin access to the workstation'],
 procedure:['Check Task Manager for a process consuming excessive CPU, memory or disk.','Check available free disk space on the system drive.','Check for pending Windows updates or a stuck update installation.','Run a malware scan if resource usage is unexplained.','Check startup programs for unnecessary items.'],
 commands:[{cmd:'Get-Process | Sort-Object CPU -Descending | Select-Object -First 10',verifies:'Identifies top CPU-consuming processes'},{cmd:'Get-PSDrive C',verifies:'Confirms free disk space on the system drive'}],
 verification:'Monitor Task Manager after remediation',
 expectedResult:'CPU/memory/disk usage returns to normal idle levels',
 rollback:'Not applicable.',
 notes:''},
{code:'KB-M365-001',title:'Outlook / Microsoft 365 Sign-in Issues',category:'Microsoft 365',tags:['outlook','m365','office 365','cannot sign in','email down'],
 purpose:'Resolve a user unable to sign in to Outlook or Microsoft 365.',
 problem:'User cannot sign in to Outlook or another Microsoft 365 app.',
 symptoms:['Repeated credential prompt in Outlook','"Something went wrong" sign-in error'],
 requirements:['Microsoft 365 admin center access'],
 procedure:['Confirm the user’s AD/Entra account is enabled and not locked.','Check for an active service health incident in the Microsoft 365 admin center.','Confirm MFA is registered and functioning for the user.','Clear cached credentials (Credential Manager) and retry sign-in.','Recreate the Outlook profile if the issue is isolated to one app.'],
 commands:[{cmd:'Get-MsolUser -UserPrincipalName user@contoso.com',verifies:'Confirms account status in Microsoft 365 (where Entra sync is in use)'}],
 verification:'User successfully signs in to Outlook',
 expectedResult:'Outlook connects and mail synchronizes',
 rollback:'Not applicable.',
 notes:''},
{code:'KB-SEC-001',title:'Suspected Phishing Email Handling',category:'Security',tags:['phishing','suspicious email','spam'],
 purpose:'Respond safely to a user-reported suspicious or phishing email.',
 problem:'A user has received a suspicious email requesting credentials, payment, or containing a suspicious link/attachment.',
 symptoms:['Unexpected sender requesting urgent action','Link or attachment the user did not expect'],
 requirements:[],
 procedure:['Do not click links or open attachments in the reported message.','Confirm the sender address and headers.','Check if other users received the same message.','Block the sender domain and purge the message if confirmed malicious.','Advise the user to change their password if they clicked a link or entered credentials.'],
 commands:[],
 verification:'Confirm the message is removed from all mailboxes it was delivered to',
 expectedResult:'Message purged, sender blocked',
 rollback:'Not applicable.',
 notes:'Never enter credentials into a page linked from a suspicious email, even to "test" it.'},
{code:'KB-APP-001',title:'Line-of-Business Application Crash Troubleshooting',category:'Applications',tags:['app crash','application not responding','software error'],
 purpose:'Diagnose a business application that crashes or fails to launch.',
 problem:'An application crashes on launch or during use.',
 symptoms:['Application closes unexpectedly','Error dialog referencing a missing file or exception'],
 requirements:['Access to Windows Event Viewer on the affected machine'],
 procedure:['Reproduce the issue and note the exact error message.','Check the Windows Application event log for the corresponding error.','Confirm the application and any required runtime (e.g. .NET) are up to date.','Try running as a different user profile to rule out a corrupt profile.','Reinstall the application if a repair does not resolve it.'],
 commands:[{cmd:'Get-WinEvent -LogName Application -MaxEvents 20',verifies:'Shows recent application-level errors'}],
 verification:'Relaunch the application',
 expectedResult:'Application opens and functions without error',
 rollback:'Restore the previous application version if a recent update caused the issue.',
 notes:''},
{code:'KB-TRB-001',title:'General Workstation Hardware Diagnostic Checklist',category:'Troubleshooting',tags:['hardware','general troubleshooting','diagnostic checklist'],
 purpose:'A general first-response checklist for hardware-related reports before deeper diagnosis.',
 problem:'A workstation or peripheral is misbehaving with no specific error identified yet.',
 symptoms:['Vague report such as "it’s not working"'],
 requirements:[],
 procedure:['Confirm power and cabling.','Confirm the device is recognized in Device Manager.','Check for pending driver or firmware updates.','Test with a known-good cable/port/peripheral to isolate the fault.','Escalate to the specific KB article once the fault is identified (network, printer, AD, etc.).'],
 commands:[{cmd:'Get-PnpDevice | Where-Object Status -ne "OK"',verifies:'Lists devices with a driver or hardware problem'}],
 verification:'Device functions normally after remediation',
 expectedResult:'No error in Device Manager, device operates as expected',
 rollback:'Not applicable.',
 notes:''},
{code:'KB-SOP-001',title:'New Employee IT Onboarding Procedure',category:'SOP',tags:['onboarding','new user','new hire'],
 purpose:'Standard procedure for provisioning IT access for a new employee.',
 problem:'N/A — standard operating procedure.',
 symptoms:[],
 requirements:['Approved new-hire request from HR with department, title and start date'],
 procedure:['Create the AD user account in the correct OU with standard naming convention.','Add the user to the relevant department security groups.','Provision a mailbox and license in Microsoft 365.','Provision a workstation and join it to the domain.','Set an initial password with "change at next logon" and issue credentials securely.','Confirm the user can log in and access required systems on day one.'],
 commands:[{cmd:'New-ADUser -Name "Full Name" -SamAccountName username -Path "OU=Department,DC=contoso,DC=com" -Enabled $true -ChangePasswordAtLogon $true',verifies:'Creates the account in the correct OU'}],
 verification:'Get-ADUser username -Properties MemberOf,Enabled',
 expectedResult:'Account is enabled and a member of the expected groups',
 rollback:'Disable-ADAccount -Identity username (if the request is cancelled)',
 notes:''},
{code:'KB-POL-001',title:'Password Policy Reference',category:'Policies',tags:['password policy','complexity','expiry policy'],
 purpose:'Reference for the organization’s current password policy.',
 problem:'N/A — policy reference.',
 symptoms:[],
 requirements:[],
 procedure:['Minimum length: 12 characters.','Complexity required: upper, lower, number, symbol.','Maximum password age: 90 days.','Account lockout threshold: 5 invalid attempts.','Lockout duration: 30 minutes or Help Desk unlock.'],
 commands:[{cmd:'Get-ADDefaultDomainPasswordPolicy',verifies:'Displays the current domain password policy'}],
 verification:'Get-ADDefaultDomainPasswordPolicy',
 expectedResult:'Returned values match the documented policy above',
 rollback:'Not applicable.',
 notes:'Contact IT management before proposing a policy change — this article is a reference, not an approval to modify policy.'},
];
